language: go
go:
- 1.6
install:
- go get -v github.com/Masterminds/glide
- glide install
- go build
deploy:
  provider: releases
  api_key:
    secure: VWXlWLf9ELrEe19JhIH54ALIMt8/JtQb1XAQ6zrwbot7umoEOMuClhFHg5bgR8GDpZJfYJiXXKap2qET4aA7kTDJyIw2/ft9GQxp01qx5RVildm2+tdr4uto4EXNc4himeFeXCUIc7ZhpKxHqQAVYy3iytEOcA7QRpmQjSp6gkJOk04ZQ39oitRRmvPPaprigtOEiDuvME/u9N55kJmkJM7xY75W04Ud7SQ5JTNtnwo79MCZEZL2x5PzVBRHO7w4YCj7BL+WW+yGeDi7/GOYloTtlpjBjcrcQo3ksg4VAr7Y7YHwaaQR3edmI0cJe5iscKrzyNtuXogSJ5CSowI7c4Fi5USASCpGb2OusF/km0ycCPmT0wvj01Rmtcqf7NLutvQ3JlhttBi0jbIq1JsdvkowbwDaZRXUTGzxvj6VqInqcXIlIKh174anTnCxZUgCPqn+rsLiO3/Zufhc7NEyDjCdABUDI+BPaAnleweCu94a5vRLGmIQpf4vhAUmnHEPuSdrCqAsyiKbBVuBXyCy0Rdma65VecZ5TmSeBbuwovsOkWRkpszfDrlA8GwKfDOckcmyg3hT46cu3XNFSnyCsnwMN7pxCS8YhjYB3852QtB4oU5mE4go2SSZhathmAMhTrNIrnTpbaPNtgZvjM1HEZvTZS/7HjHSQrohxazEtr4=
  file: ./myna
  on:
    repo: SpectoLabs/myna
